services:
  memdb:
    build:
      context: .
      dockerfile: Dockerfile
    image: memdb:latest
    container_name: memdb
#    volumes:
#      - mdb-data:/mdb/data
    env_file:
      - .env
    environment:
      - TZ=America/Los_Angeles
    ports:
      - "8899:7899"
      - "8900:7900"
      - "8901:7901"
      - "8902:7902"
volumes:
  mdb-data:
